INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("1","lapiceros", "bolik",3,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("2","lapiz", "bolik",2,8);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("3","plumas", "faber castell",5,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("4","borradores", "pelican",1,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("5","zacapuntas", "pelican",0.50,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("6","estucheras", "norma",15,5);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("7","cuadernos de 80 hojas", "norma",4.50,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("8","cuadernos de 100 hojas", "norma",5.00,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("9","folders", "office",1.00,25);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("10","hojas en blanco", "",0.20,300);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("11","hojas de cuadros", "",0.20,300);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("12","temperas", "tucan",10,5);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("13","pinceles", "tucan",1.00,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("14","acuarelas", "faber castell",10,5);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("15","bolsones", "animados",150,5);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("16","grapadoras", "",15,4);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("17","grapas", "",5,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("18","hojas de colores", "office",0.50,100);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("19","papel china", "office",0.50,100);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("20","cartulinas", "oficce",3.00,30);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("21","lapiceros pilot", "pilot",5,15);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("22","lapiceros bic", "bic",2.00,20);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("23","pegamento pequeno", "elefante",5.00,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("24","pegamento grande", "elefante",9.00,8);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("25","crayones", "norma",8.00,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("26","reglas", "rule",1,20);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("27","compas", "fabik",8,5);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("28","marcadores negros", "fabik",4.00,7);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("29","moñas", "",1,20);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("30","papel de regalo variado", "",3.00,25);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("31","nylon", "",3,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("32","grapadoras", "",10.00,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("33","sacabocados", "",8.00,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("34","calculadoras cientificas", "casio",120.00,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("35","libros de lectura", "",20,50);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("36","calculadoras pequeñas", "casio",25,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("37","cinta adesiva", "bolik",5,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("38","estampas animadas", "variados",5,15);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("39","bolas de regalo", "",5,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("40","duropor", "",5,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("41","juego de escuadras", "standler",10.00,5);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("42","folder de color", "office",2,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("43","tijeras", "",5,5);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("44","plasticina", "fabik",5,10);
INSERT INTO `productos` (`codigo`,`descripcion`,`marca`,`precio_venta`,`existencia_minima`) VALUES ("45","cilicon", "",1.00,20);
